apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: userservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 40
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-celery-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-celery-worker
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: user-celery-beat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-celery-beat
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40
