apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: courseservice
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: courseservice
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: course-celery-worker
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: course-celery-worker
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: course-celery-beat
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: course-celery-beat
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 60