apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
   name: waycool2o-be-censanext
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: waycool2o-be-censanext  
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40